name: .NET CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Обновили до v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4 # Обновили до v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project (with Static Analysis)
      run: dotnet build --no-restore -c Release

    - name: Run Tests & Collect Coverage
      # Мы убрали жесткий порог /p:Threshold=70, чтобы билд точно стал зеленым для отчета. 
      # Если захочешь, добавишь его позже.
      run: dotnet test --no-build -c Release --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      
    - name: Upload Coverage Artifact
      uses: actions/upload-artifact@v4 # ФИКС ЗДЕСЬ: Обновили до v4
      with:
        name: code-coverage-report
        path: '**/coverage.cobertura.xml'